image:
  repository: postfix
  pullPolicy: IfNotPresent
  tag: "latest"

daemonset:
  resources:
    requests:
      cpu: 200m
      memory: 200Mi
    limits:
      cpu: 400m
      memory: 800Mi
  containerPort: 587
