apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postfix.fullname" . }}-configmap
data:
  main.cf: |
    maillog_file = /var/log/mail.log

    relayhost = smtp.gmail.com:587
    smtp_sasl_auth_enable = yes
    smtp_sasl_mechanism_filter =
    smtp_sasl_security_options =
    smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
